language: go

before_cache:
-  find $GOPATH/pkg/**/github.com/vjeantet/bitfan/* -maxdepth 0 ! -name vendor -print0 | xargs -0 rm -rf

cache:
  directories:
    - $GOPATH/pkg
   
install:
    - go get -v golang.org/x/tools/cmd/cover
    - go get -v github.com/stretchr/testify/assert
script:
    - go get -v github.com/go-playground/overalls
    - overalls -project=github.com/vjeantet/bitfan -covermode=count -ignore=vendor,.git,docs,.bitfan,data,examples.d,releases -concurrency=2
after_success:
    - go get -v github.com/mattn/goveralls
    - export PATH=$PATH:$HOME/gopath/bin
    - goveralls -coverprofile=overalls.coverprofile -service=travis-ci
    - test -n "$TRAVIS_TAG" && go get github.com/goreleaser/goreleaser && goreleaser 
