baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "hugo-theme-docdock"

title = "Bitfan"

[params]
editURL = "https://github.com/vjeantet/bitfan/edit/master/docs/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = false # default is false
unfoldedMenus = ["start"] # set menu identifiers which should be displayed unfolded  
# themeVariant = "green" # choose theme variant "green", "gold" , "blue" (default)


[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "repo"
url = "https://github.com/vjeantet/bitfan"
weight = 1

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Credits & Contributors"
url = "/credits"
weight = 3

[[menu.shortcuts]]
name = '<img src="https://godoc.org/github.com/vjeantet/bitfan?status.svg" alt="GoDoc" style="width: auto; height: auto;">'
identifier = "godoc"
url = "https://godoc.org/github.com/vjeantet/bitfan"
weight = 200